### ISSUE TITLE
delete this soft bullshit

### ISSUE THREAD

**Issue by Vincouux** [theomatas/Brain_Bros#5]

**Comment by danielbaud** [comment]
yes please

**Comment by Choqs** [comment]
Closing due to duplicate

**Comment by Choqs** [comment]
@dgse please review

**Comment by danielbaud** [comment]
I tried but I can't seem to find where to fucking start
pls send help

**Comment by danielbaud** [comment]
[https://www.defense.gouv.fr/dgse](click here) to get some help

**Comment by Choqs** [comment]
ok done, what should I do next?
